    const studentRichMenuObject = JSON.parse(fs.readFileSync(path.resolve(__dirname, 'rich_menu', 'student_rich_menu.json'), 'utf8'));
    const studentRichMenuId = await client.createRichMenu(studentRichMenuObject);
    // ...
    const studentImageStream = fs.createReadStream(path.resolve(__dirname, 'rich_menu', 'student_rich_menu.png'));
    // ...
    const teacherRichMenuObject = JSON.parse(fs.readFileSync(path.resolve(__dirname, 'rich_menu', 'teacher_rich_menu.json'), 'utf8'));
    const teacherRichMenuId = await client.createRichMenu(teacherRichMenuObject);
    // ...
    const teacherImageStream = fs.createReadStream(path.resolve(__dirname, 'rich_menu', 'teacher_rich_menu.png'));
