// migrations/xxxxxxxxxxxx_initial_schema.js

exports.shorthands = undefined;

/**
 * @param {import("node-pg-migrate/dist/types").MigrationBuilder} pgm
  */
  exports.up = pgm => {
      console.log("▶️ Running initial schema migration: Creating all tables and indexes...");

          // 建立 users 表格
              pgm.createTable('users', {
                      id: { type: 'varchar(255)', primaryKey: true },
                              name: { type: 'varchar(255)', notNull: true },
                                      points: { type: 'integer', default: 0 },
                                              role: { type: 'varchar(50)', default: 'student' },
                                                      history: { type: 'jsonb', default: '[]' },
                                                              last_seen_announcement_id: { type: 'integer', default: 0 },
                                                                      picture_url: { type: 'text' },
                                                                              approved_by: { type: 'varchar(255)' }
                                                                                  });

                                                                                      // 建立 courses 表格
                                                                                          pgm.createTable('courses', {
                                                                                                  id: { type: 'varchar(255)', primaryKey: true },
                                                                                                          title: { type: 'varchar(255)', notNull: true },
                                                                                                                  time: { type: 'timestamptz', notNull: true },
                                                                                                                          capacity: { type: 'integer', notNull: true },
                                                                                                                                  points_cost: { type: 'integer', notNull: true },
                                                                                                                                          students: { type: 'text[]', default: '{}' },
                                                                                                                                                  waiting: { type: 'text[]', default: '{}' }
                                                                                                                                                      });

                                                                                                                                                          // 建立 orders 表格
                                                                                                                                                              pgm.createTable('orders', {
                                                                                                                                                                      order_id: { type: 'varchar(255)', primaryKey: true },
                                                                                                                                                                              user_id: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                      user_name: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                              points: { type: 'integer', notNull: true },
                                                                                                                                                                                                      amount: { type: 'integer', notNull: true },
                                                                                                                                                                                                              last_5_digits: { type: 'varchar(5)' },
                                                                                                                                                                                                                      status: { type: 'varchar(50)', notNull: true },
                                                                                                                                                                                                                              timestamp: { type: 'timestamptz', notNull: true }
                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                      // 建立 feedback_messages 表格
                                                                                                                                                                                                                                          pgm.createTable('feedback_messages', {
                                                                                                                                                                                                                                                  id: { type: 'varchar(255)', primaryKey: true },
                                                                                                                                                                                                                                                          user_id: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                  user_name: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                          message: { type: 'text', notNull: true },
                                                                                                                                                                                                                                                                                  status: { type: 'varchar(50)', default: 'new' },
                                                                                                                                                                                                                                                                                          timestamp: { type: 'timestamptz', notNull: true },
                                                                                                                                                                                                                                                                                                  teacher_reply: { type: 'text' },
                                                                                                                                                                                                                                                                                                          is_student_read: { type: 'boolean', notNull: true, default: false }
                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                  // 建立 announcements 表格
                                                                                                                                                                                                                                                                                                                      pgm.createTable('announcements', {
                                                                                                                                                                                                                                                                                                                              id: { type: 'serial', primaryKey: true },
                                                                                                                                                                                                                                                                                                                                      content: { type: 'text', notNull: true },
                                                                                                                                                                                                                                                                                                                                              created_at: { type: 'timestamptz', default: pgm.func('now()') },
                                                                                                                                                                                                                                                                                                                                                      creator_id: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                              creator_name: { type: 'varchar(255)', notNull: true }
                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                      // 建立 products 表格
                                                                                                                                                                                                                                                                                                                                                                          pgm.createTable('products', {
                                                                                                                                                                                                                                                                                                                                                                                  id: { type: 'serial', primaryKey: true },
                                                                                                                                                                                                                                                                                                                                                                                          name: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                  description: { type: 'text' },
                                                                                                                                                                                                                                                                                                                                                                                                          price: { type: 'integer', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                  image_url: { type: 'text' },
                                                                                                                                                                                                                                                                                                                                                                                                                          inventory: { type: 'integer', notNull: true, default: 0 },
                                                                                                                                                                                                                                                                                                                                                                                                                                  status: { type: 'varchar(50)', default: 'available' },
                                                                                                                                                                                                                                                                                                                                                                                                                                          creator_id: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  creator_name: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          created_at: { type: 'timestamptz', default: pgm.func('now()') }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // 建立 product_orders 表格
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pgm.createTable('product_orders', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id: { type: 'serial', primaryKey: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      order_uid: { type: 'varchar(255)', unique: true, notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              user_id: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user_name: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              product_id: { type: 'integer', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      product_name: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              points_spent: { type: 'integer', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      status: { type: 'varchar(50)', notNull: true, default: 'pending' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              created_at: { type: 'timestamptz', default: pgm.func('now()') },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updated_at: { type: 'timestamptz' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              teacher_notes: { type: 'text' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // 建立 tasks 表格
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pgm.createTable('tasks', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id: { type: 'serial', primaryKey: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          recipient_id: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message_payload: { type: 'jsonb', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          status: { type: 'varchar(50)', notNull: true, default: 'pending' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  send_at: { type: 'timestamptz', notNull: true, default: pgm.func('now()') },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          retry_count: { type: 'integer', default: 0 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  last_error: { type: 'text' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          created_at: { type: 'timestamptz', default: pgm.func('now()') },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  updated_at: { type: 'timestamptz', default: pgm.func('now()') }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // 建立 system_settings 表格
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              pgm.createTable('system_settings', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setting_key: { type: 'varchar(100)', primaryKey: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setting_value: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updated_at: { type: 'timestamptz', default: pgm.func('now()') }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              pgm.sql("INSERT INTO system_settings (setting_key, setting_value) VALUES ('notifications_enabled', 'true') ON CONFLICT (setting_key) DO NOTHING");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // 建立 failed_tasks 表格
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pgm.createTable('failed_tasks', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id: { type: 'serial', primaryKey: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      original_task_id: { type: 'integer' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              recipient_id: { type: 'varchar(255)', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      message_payload: { type: 'jsonb', notNull: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              last_error: { type: 'text' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      failed_at: { type: 'timestamptz', default: pgm.func('now()') }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 建立所有索引
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("   -> Creating indexes...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pgm.createIndex('users', 'role');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pgm.createIndex('courses', 'time');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              pgm.createIndex('orders', 'status');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  pgm.createIndex('products', 'status');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pgm.createIndex('orders', 'user_id');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pgm.createIndex('product_orders', 'user_id');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              pgm.createIndex('courses', 'students', { method: 'gin' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  pgm.createIndex('courses', 'waiting', { method: 'gin' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pgm.createIndex('tasks', ['status', 'send_at']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("✅ Initial schema migration finished.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * @param {import("node-pg-migrate/dist/types").MigrationBuilder} pgm
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exports.down = pgm => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log("⏪ Rolling back initial schema migration...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pgm.dropTable('failed_tasks');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pgm.dropTable('system_settings');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pgm.dropTable('tasks');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pgm.dropTable('product_orders');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pgm.dropTable('products');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pgm.dropTable('announcements');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pgm.dropTable('feedback_messages');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pgm.dropTable('orders');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pgm.dropTable('courses');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pgm.dropTable('users');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("⏪ Rollback finished.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                